Tweak test steps

diff --git a/.github/workflows/linux-test.yml b/.github/workflows/linux-test.yml
--- a/.github/workflows/linux-test.yml
+++ b/.github/workflows/linux-test.yml
@@ -19,10 +19,12 @@ jobs:
         run: |
           rm ./install.sh
           ls
-      - name: 👉🏽 Test edge-impulse-cli
+      - name: 👉🏽 Test uploader
         run: |
           set +e # Ignore Errors
           OUTPUT=$(edge-impulse-uploader --api-key notarealkey --category training path/to/file.wav 2>&1)
-          if [ "$OUTPUT" == *"Invalid API key"* ]; then echo "Failed as expected!"; else echo "Test failed!" fi
+          if [ "$OUTPUT" == *"Invalid API key"* ]; then echo "Failed as expected!"; else echo "Test failed!" && exit 1; fi
+      - name: 👉🏽 Test serialport
+        run: |
           set -e # Throw Errors
           edge-impulse-daemon --version
