Fix test syntax

diff --git a/.github/workflows/linux-test.yml b/.github/workflows/linux-test.yml
--- a/.github/workflows/linux-test.yml
+++ b/.github/workflows/linux-test.yml
@@ -28,4 +28,10 @@ jobs:
           set +e # Ignore Errors
           OUTPUT=$(edge-impulse-uploader --api-key notarealkey --category training path/to/file.wav 2>&1)
           echo $OUTPUT
-          if [ "$OUTPUT" == *"Invalid API key"* ]; then echo "Failed as expected!"; else echo "Test failed!" && exit 1; fi
+          if [[ "$OUTPUT" == *"Invalid API key"* ]]; then
+            echo "Upload failed with invalid credentials as expected!"
+          else
+            echo "Expected invalid credentials failure but instead got:"
+            echo "$OUTPUT!"
+            exit 1
+          fi
